name: Executar Script Python

on:
  schedule:
    - cron: '0 * * * *'  # Roda todo início de hora
  workflow_dispatch:     # Permite execução manual

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Restaurar service_account.json
        run: |
          mkdir -p GOOGLE_CREDENTIALS
          echo "${{ secrets.GOOGLE_CREDENTIALS }}" | base64 -d > GOOGLE_CREDENTIALS/service_account.json
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Instalar Dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar o script
        run: python Robô.murilo.py
