name: Executar Script Python

on:
  schedule:
    - cron: '0 * * * *'  # Roda a cada hora, no minuto 0
  workflow_dispatch:        # Permite execução manual

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4
      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar Dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configurar Credenciais (Conta de Serviço)
        env:

          echo "$GOOGLE_CREDENTIALS" | base64 -d > credentials.json
        env:
          GCP_JSON_BASE64: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install chromium

      - name: Executar o script
        run: python Robô.murilo.py
